spring:
  application:
    name: configuration-service
#  config:
#    import: "optional:configserver:http://localhost:8088"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/salarysetup
    password: root
  security:
    user:
      name: admin
      password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
  #application-specific string used to encrypt tokens
  # token valid for 10 minutes
security:
  jwt:
    token:
      jwtSecret: ======================Adoga=Spring===========================
      jwtExpirationMs: 600000
#login:
#  url:
#   path: /users/login
authorization:
  token:
   header:
      name: Authorization
      prefix: Bearer
users:
  exceptions:
   user-not-found: User not found!
albums:
  exceptions:
   albums-not-found: User albums not found!
server:
  port: 8082





